
CREATE DATABASE IF NOT EXISTS db82 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE db82;

DROP TABLE IF EXISTS writeoffs;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS borrowings;
DROP TABLE IF EXISTS bookcategories;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS publishers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
  RoleID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (RoleID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
  UserID INT NOT NULL AUTO_INCREMENT,
  Login VARCHAR(50) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Surname VARCHAR(50) DEFAULT NULL,
  Patronymic VARCHAR(50) DEFAULT NULL,
  Role INT DEFAULT NULL,
  PRIMARY KEY (UserID),
  KEY Role (Role),
  CONSTRAINT Users_ibfk_1 FOREIGN KEY (Role) REFERENCES roles (RoleID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE authors (
  AuthorID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Surname VARCHAR(50) NOT NULL,
  Patronymic VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (AuthorID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE categories (
  CategoryID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (CategoryID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE publishers (
  PublisherID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (PublisherID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE groups (
  GroupID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (GroupID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE students (
  StudentID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Surname VARCHAR(50) NOT NULL,
  Patronymic VARCHAR(50) DEFAULT NULL,
  `Group` INT DEFAULT NULL,
  Phone VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (StudentID),
  KEY `Group` (`Group`),
  CONSTRAINT Students_ibfk_1 FOREIGN KEY (`Group`) REFERENCES groups (GroupID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE books (
  BookID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(100) NOT NULL,
  AuthorOne INT NOT NULL,
  AuthorTwo INT DEFAULT NULL,
  Publisher INT DEFAULT NULL,
  Year INT DEFAULT NULL,
  AvailableNow INT DEFAULT 0,
  Count INT DEFAULT 0,
  ImagePath LONGBLOB DEFAULT NULL,
  PRIMARY KEY (BookID),
  KEY AuthorOne (AuthorOne),
  KEY AuthorTwo (AuthorTwo),
  KEY fk_publisher (Publisher),
  CONSTRAINT Books_ibfk_1 FOREIGN KEY (AuthorOne) REFERENCES authors (AuthorID),
  CONSTRAINT Books_ibfk_2 FOREIGN KEY (AuthorTwo) REFERENCES authors (AuthorID),
  CONSTRAINT fk_publisher FOREIGN KEY (Publisher) REFERENCES publishers (PublisherID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE bookcategories (
  BookID INT NOT NULL,
  CategoryID INT NOT NULL,
  PRIMARY KEY (BookID, CategoryID),
  KEY CategoryID (CategoryID),
  CONSTRAINT BookCategories_ibfk_1 FOREIGN KEY (BookID) REFERENCES books (BookID),
  CONSTRAINT BookCategories_ibfk_2 FOREIGN KEY (CategoryID) REFERENCES categories (CategoryID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE borrowings (
  BorrowingID INT NOT NULL AUTO_INCREMENT,
  StudentID INT NOT NULL,
  BookID INT NOT NULL,
  BorrowDate VARCHAR(20) NOT NULL,
  ReturnDate VARCHAR(20) DEFAULT NULL,
  Count INT DEFAULT NULL,
  PRIMARY KEY (BorrowingID),
  KEY StudentID (StudentID),
  KEY BookID (BookID),
  CONSTRAINT Borrowings_ibfk_1 FOREIGN KEY (StudentID) REFERENCES students (StudentID),
  CONSTRAINT Borrowings_ibfk_2 FOREIGN KEY (BookID) REFERENCES books (BookID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE purchases (
  PurchaseID INT NOT NULL AUTO_INCREMENT,
  BookID INT NOT NULL,
  Date DATE NOT NULL,
  Count INT NOT NULL,
  PRIMARY KEY (PurchaseID),
  KEY BookID (BookID),
  CONSTRAINT purchases_ibfk_1 FOREIGN KEY (BookID) REFERENCES books (BookID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE writeoffs (
  WriteOffID INT NOT NULL AUTO_INCREMENT,
  BookID INT NOT NULL,
  Date DATE NOT NULL,
  Count INT NOT NULL,
  Reason VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (WriteOffID),
  KEY BookID (BookID),
  CONSTRAINT writeoffs_ibfk_1 FOREIGN KEY (BookID) REFERENCES books (BookID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;